# Use the official WordPress image with Apache and PHP 8.1
FROM wordpress:php8.1-apache
# We can add custom commands here later if needed, like:
# COPY ./custom-theme/ /var/www/html/wp-content/themes/custom-theme/