name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: CD on self-hosted
    runs-on: [self-hosted, linux, x64]

    env:
      DEPLOY_DIR: /var/www/devopst1
      ARTIFACT_NAME: deploy-artifact
      ARTIFACT_FILE: deploy.zip

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Wait for previous workflow success
      if: ${{ github.event.workflow_run.conclusion != 'success' }}
      run: |
        echo "Upstream workflow did not succeed. Exiting."
        exit 1

    - name: Download artifact from CI
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./artifact
        run-id: ${{ github.event.workflow_run.id }}  # Critical fix

    - name: Inspect artifact
      run: |
        ls -lah artifact
        file artifact/${{ env.ARTIFACT_FILE }}

    - name: Unpack and deploy
      run: |
        sudo mkdir -p $DEPLOY_DIR
        sudo chown -R $USER:$USER $DEPLOY_DIR
        unzip -o artifact/${{ env.ARTIFACT_FILE }} -d /tmp/deploy_temp
        sudo cp -r /tmp/deploy_temp/* $DEPLOY_DIR/
        sudo chown -R www-data:www-data $DEPLOY_DIR

    - name: Deploy nginx config and reload
      run: |
        sudo nginx -t
        sudo systemctl restart nginx

    - name: Verify with curl
      run: |
        sleep 1
        curl -f http://localhost/ || (curl -v http://localhost/ && exit 1)