name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    name: Deploy to self-hosted
    runs-on: [self-hosted, linux, x64]

    env:
      DEPLOY_DIR: /var/www/devopst1

    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: deploy-artifact
          path: ./artifact
          github-token: ${{ secrets.PAT }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verify artifact exists
        run: |
          test -f ./artifact/deploy.zip || (echo "ERROR: artifact missing" && exit 1)

      - name: Extract artifact
        run: |
          mkdir -p ./deploy_extract
          unzip -o ./artifact/deploy.zip -d ./deploy_extract

      - name: Deploy to webroot
        run: |
          sudo mkdir -p "$DEPLOY_DIR"
          sudo chown -R $USER:$USER "$DEPLOY_DIR"
          rsync -a --delete ./deploy_extract/public/ "$DEPLOY_DIR/"
          sudo chown -R www-data:www-data "$DEPLOY_DIR"

      - name: Restart nginx (non-interactive)
        run: |
          sudo -n nginx -t
          sudo -n systemctl restart nginx

      - name: Quick verify
        run: |
          sleep 2
          curl -f http://localhost/ || (echo "ERROR: site did not respond" && sudo -n systemctl status nginx --no-pager && exit 1)

      - name: Cleanup
        run: |
          rm -rf ./artifact ./deploy_extract
