name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - List files
      run: ls -la

    - name: Validate HTML
      run: |
        echo "<!DOCTYPE html><title>Test</title><h1>Test" > test.html
        tidy -q -e test.html || echo "HTML validation completed"

    - name: Create deployment package
      run: zip -r deployment.zip . -x "*.git*" "*.github*"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-party-app
        path: deployment.zip

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: html-party-app

    - name: Unzip deployment package
      run: unzip -o deployment.zip -d /var/www/html-party-app

    - name: Set permissions
      run: sudo chown -R www-data:www-data /var/www/html-party-app

    - name: Setup nginx configuration
      run: |
        sudo cp nginx.conf /etc/nginx/sites-available/html-party-app
        sudo ln -sf /etc/nginx/sites-available/html-party-app /etc/nginx/sites-enabled/
        sudo nginx -t

    - name: Restart nginx
      run: sudo systemctl restart nginx

    - name: Verify deployment
      run: |
        echo "Deployment completed at $(date)" >> /var/www/html-party-app/deployment.log
        ls -la /var/www/html-party-app/
