name: Python App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/pythonapp/**'

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and pytest
        run: |
          cd apps/pythonapp
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd apps/pythonapp
          python -m pytest test_app.py -v

      - name: Archive application
        run: |
          cd apps/pythonapp
          # Exclude virtual environment and other unnecessary files
          zip -r ../../python-app.zip . -x "venv/*" "__pycache__/*" "*.pyc"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-artifact
          path: python-app.zip