name: React App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/reactapp/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: apps/reactapp

      - name: Build the app
        run: npm run build
        working-directory: apps/reactapp

      - name: Archive production build
        run: |
          cd apps/reactapp
          zip -r ../../react-build.zip dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-artifact
          path: react-build.zip