name: React App CD

on:
  workflow_run:
    workflows: [React App CI]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: self-hosted

    steps:
      - name: Check workflow context
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Head Branch: ${{ github.event.workflow_run.head_branch }}"

      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: react-artifact
          path: ./artifact
          github-token: ${{ secrets.PAT }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verify artifact
        run: |
          if [ ! -f "./artifact/react-build.zip" ]; then
            echo "Error: Artifact not found!"
            ls -la ./artifact/
            exit 1
          fi
          echo "Artifact found and verified."

      - name: Extract artifact
        run: |
          unzip -o "./artifact/react-build.zip" -d "./deploy_extract"
          if [ ! -d "./deploy_extract/dist" ]; then
            echo "Error: Extraction failed or wrong structure!"
            ls -la "./deploy_extract/"
            exit 1
          fi
          echo "Artifact extracted successfully."

      - name: Deploy to server using rsync
        run: |
          sudo -n mkdir -p /var/www/reactapp/dist/
          sudo -n chown -R $USER:$USER /var/www/reactapp/dist/
          rsync -a --delete ./deploy_extract/dist/ /var/www/reactapp/dist/
          sudo -n chown -R www-data:www-data /var/www/reactapp/dist/
          sudo -n chmod -R 755 /var/www/reactapp/dist/

      - name: Deploy Nginx config
        run: |
          sudo -n cp configs/nginx/xyz-com /etc/nginx/sites-available/xyz-com
          sudo -n ln -sf /etc/nginx/sites-available/xyz-com /etc/nginx/sites-enabled/
          sudo -n nginx -t
          sudo -n systemctl reload nginx

      - name: Cleanup
        run: |
          rm -rf ./deploy_extract
          rm -rf ./artifact
          echo "Cleanup completed."