name: React App CD

on:
  workflow_run:
    workflows: [React App CI]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-artifact
          path: react-artifact

      - name: Extract artifact
        run: |
          unzip react-artifact/react-build.zip -d react-artifact/extracted

      - name: Deploy React app
        run: |
          sudo mkdir -p /var/www/reactapp/dist/
          sudo cp -r react-artifact/extracted/dist/* /var/www/reactapp/dist/
          sudo chown -R www-data:www-data /var/www/reactapp/dist/
          sudo chmod -R 755 /var/www/reactapp/dist/

      - name: Deploy Nginx config
        run: |
          sudo cp configs/nginx/xyz-com /etc/nginx/sites-available/xyz-com
          sudo ln -sf /etc/nginx/sites-available/xyz-com /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl reload nginx